The original purpose of this code is to combine the categorized queries and the ndcg@10 values ​​from all scores into a large table.

I have already completed this task in nf_cats_all_datasets.py, combining the scores and classification results of all datasets to generate nf_cats_all_datasets_with_scores.csv.

The current task is to perform statistical analysis on the combined scores.

I want to perform LMM test analysis on the results of each model at the query granularity obtained from the experiment. This code also generates the file data/df_long_all_model_scores.csv used for LMM analysis.

In [ ]:
# 1， Load data
import numpy as np
import pandas as pd

data = pd.read_csv('data/nf_cats_all_datasets_with_scores.csv')
data

,query_id,dataset_name,raw_query_id,query_type,query_text,split,bm25_score_ndcg@10,contriever_score_ndcg@10,bge_m3_score_ndcg@10,qwen3_score_ndcg@10,linq_score_ndcg@10,gte_score_ndcg@10,reasonir_score_ndcg@10,diver_score_ndcg@10,bge_reasoner_score_ndcg@10
0,trec-covid__test__1,trec-covid,1,EVIDENCE-BASED,what is the origin of COVID-19,test,0.252841,0.039199,0.340113,1.000000,0.716937,0.784617,0.653408,0.501819,0.778429
1,trec-covid__test__2,trec-covid,2,EVIDENCE-BASED,how does the coronavirus respond to changes in...,test,0.613283,0.252841,0.864315,1.000000,1.000000,0.861138,0.926636,1.000000,0.921602
2,trec-covid__test__3,trec-covid,3,DEBATE,will SARS-CoV2 infected people develop immunit...,test,0.195189,0.894275,0.000000,1.000000,0.930569,0.899030,0.827749,0.826422,0.650414
3,trec-covid__test__4,trec-covid,4,EVIDENCE-BASED,what causes death from Covid-19?,test,0.135685,0.110046,0.314880,1.000000,0.966873,0.965284,0.591945,0.957428,0.831848
4,trec-covid__test__5,trec-covid,5,EVIDENCE-BASED,what drugs have been active against SARS-CoV o...,test,0.519520,0.508287,0.283713,1.000000,0.743345,0.546287,0.706663,0.671759,0.571936
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42519,msmarco__test__1132532,msmarco,1132532,FACTOID,average annual income data analyst,test,0.428797,0.835746,0.889954,1.000000,0.978793,0.976856,0.776182,0.770499,0.898255
42520,msmarco__test__1133579,msmarco,1133579,EVIDENCE-BASED,how does granulation tissue start,test,0.554417,0.629336,0.812214,0.818852,0.817511,0.627877,0.652478,0.676379,0.741429
42521,msmarco__test__1136043,msmarco,1136043,FACTOID,difference between a hotel and motel,test,0.346317,0.805447,0.724774,0.725397,0.724774,0.723278,0.618023,0.683002,0.593403
42522,msmarco__test__1136047,msmarco,1136047,FACTOID,difference between a company's strategy and bu...,test,0.459095,0.327582,0.475790,0.557774,0.613942,0.371733,0.433620,0.461970,0.305609
42523,msmarco__test__1136962,msmarco,1136962,REASON,why did the ancient egyptians call their land ...,test,0.736643,0.693325,0.926636,0.814791,0.848238,0.865011,0.881292,0.880349,0.863444

In [ ]:
# 2, Statistical Analysis

# Statistically analyze the performance of each model on each specific dataset (dataset_name), calculating the mean and standard deviation of ndcg@10.

# This yields the performance on each dataset, which should be consistent with the wandb results.
model_name_list = ['bm25','contriever', 'bge_m3', 'qwen3', 'linq', 'gte', 'reasonir', 'diver', 'bge_reasoner']

dataset_results = []
for model in model_name_list:
    col = f"{model}_score_ndcg@10"
    grouped_dataset = data.groupby(['dataset_name'])[col].agg(
        ['mean', 'std', 'min', 'max', 'count']).reset_index()
    print(f"Processed model: {model}")
    print(grouped_dataset)

Processed model: bm25
           dataset_name      mean       std       min       max  count
0                  aops  0.061984  0.149995  0.000000  0.765361    111
1               arguana  0.386585  0.352681  0.000000  1.000000   1406
2               biology  0.188905  0.273033  0.000000  1.000000    103
3       browsecomp_plus  0.043886  0.119771  0.000000  0.831872    830
4         climate-fever  0.151630  0.236297  0.000000  1.000000   1535
5        dbpedia-entity  0.309808  0.269749  0.000000  1.000000    400
6         earth_science  0.271736  0.298246  0.000000  1.000000    116
7             economics  0.148705  0.268324  0.000000  1.000000    103
8                 fever  0.602849  0.385046  0.000000  1.000000   6666
9                  fiqa  0.236742  0.319568  0.000000  1.000000    648
10             hotpotqa  0.600760  0.278795  0.000000  1.000000   7405
11             leetcode  0.241021  0.339225  0.000000  1.000000    142
12              msmarco  0.221301  0.326066  0.000000  1.000000   7077
13             nfcorpus  0.314056  0.319331  0.000000  1.000000    323
14                   nq  0.294814  0.355077  0.000000  1.000000   3452
15                 pony  0.078613  0.107497  0.000000  0.494640    112
16           psychology  0.125290  0.243000  0.000000  1.000000    101
17                quora  0.769127  0.327340  0.000000  1.000000  10000
18             robotics  0.135833  0.233152  0.000000  1.000000    101
19              scidocs  0.144143  0.203627  0.000000  1.000000   1000
20              scifact  0.670755  0.379551  0.000000  1.000000    300
21        stackoverflow  0.184345  0.301087  0.000000  1.000000    117
22   sustainable_living  0.149973  0.255015  0.000000  1.000000    108
23  theoremqa_questions  0.103640  0.261991  0.000000  1.000000    194
24   theoremqa_theorems  0.049416  0.149824  0.000000  0.831555     75
25           trec-covid  0.528828  0.271091  0.078398  1.000000     50
26     webis-touche2020  0.444244  0.195816  0.000000  0.849670     49
Processed model: contriever
           dataset_name      mean       std  min       max  count
0                  aops  0.098330  0.198529  0.0  0.795750    111
1               arguana  0.445418  0.352851  0.0  1.000000   1406
2               biology  0.189899  0.268172  0.0  1.000000    103
3       browsecomp_plus  0.068910  0.152705  0.0  1.000000    830
4         climate-fever  0.237859  0.278392  0.0  1.000000   1535
5        dbpedia-entity  0.413144  0.271565  0.0  1.000000    400
6         earth_science  0.282695  0.337115  0.0  1.000000    116
7             economics  0.174369  0.294618  0.0  1.000000    103
8                 fever  0.757460  0.315373  0.0  1.000000   6666
9                  fiqa  0.330361  0.341311  0.0  1.000000    648
10             hotpotqa  0.637597  0.274765  0.0  1.000000   7405
11             leetcode  0.221722  0.331632  0.0  1.000000    142
12              msmarco  0.410740  0.376010  0.0  1.000000   7077
13             nfcorpus  0.327866  0.315168  0.0  1.000000    323
14                   nq  0.498054  0.374058  0.0  1.000000   3452
15                 pony  0.097650  0.113146  0.0  0.630930    112
16           psychology  0.162436  0.272259  0.0  1.000000    101
17                quora  0.864355  0.249906  0.0  1.000000  10000
18             robotics  0.140805  0.267867  0.0  1.000000    101
19              scidocs  0.165929  0.211642  0.0  1.000000   1000
20              scifact  0.676665  0.389108  0.0  1.000000    300
21        stackoverflow  0.142184  0.233134  0.0  1.000000    117
22   sustainable_living  0.143156  0.249499  0.0  1.000000    108
23  theoremqa_questions  0.100714  0.271403  0.0  1.000000    194
24   theoremqa_theorems  0.039693  0.172645  0.0  1.000000     75
25           trec-covid  0.593798  0.295137  0.0  1.000000     50
26     webis-touche2020  0.204519  0.209928  0.0  0.881579     49
Processed model: bge_m3
           dataset_name      mean       std  min       max  count
0                  aops  0.045544  0.149670  0.0  0.802038    111
1               arguana  0.540136  0.350517  0.0  1.000000   1406
2               biology  0.103331  0.211362  0.0  1.000000    103
3       browsecomp_plus  0.062936  0.145829  0.0  1.000000    830
4         climate-fever  0.296594  0.295605  0.0  1.000000   1535
5        dbpedia-entity  0.398264  0.259022  0.0  1.000000    400
6         earth_science  0.175432  0.293540  0.0  1.000000    116
7             economics  0.111026  0.234147  0.0  1.000000    103
8                 fever  0.809183  0.277928  0.0  1.000000   6666
9                  fiqa  0.410646  0.362846  0.0  1.000000    648
10             hotpotqa  0.694619  0.279780  0.0  1.000000   7405
11             leetcode  0.246852  0.346847  0.0  1.000000    142
12              msmarco  0.387654  0.378451  0.0  1.000000   7077
13             nfcorpus  0.316361  0.309970  0.0  1.000000    323
14                   nq  0.606213  0.372672  0.0  1.000000   3452
15                 pony  0.147851  0.134567  0.0  0.544221    112
16           psychology  0.145457  0.246398  0.0  1.000000    101
17                quora  0.885569  0.229957  0.0  1.000000  10000
18             robotics  0.112088  0.223513  0.0  1.000000    101
19              scidocs  0.164188  0.207468  0.0  0.989606   1000
20              scifact  0.641333  0.398298  0.0  1.000000    300
21        stackoverflow  0.090654  0.188612  0.0  1.000000    117
22   sustainable_living  0.100491  0.200847  0.0  1.000000    108
23  theoremqa_questions  0.128608  0.292586  0.0  1.000000    194
24   theoremqa_theorems  0.051594  0.184850  0.0  0.919721     75
25           trec-covid  0.556140  0.287369  0.0  1.000000     50
26     webis-touche2020  0.221467  0.217605  0.0  0.942293     49
Processed model: qwen3
           dataset_name      mean       std       min       max  count
0                  aops  0.096862  0.185057  0.000000  1.000000    111
1               arguana  0.766358  0.282217  0.000000  1.000000   1406
2               biology  0.197433  0.268795  0.000000  1.000000    103
3       browsecomp_plus  0.199991  0.245247  0.000000  1.000000    830
4         climate-fever  0.473765  0.317798  0.000000  1.000000   1535
5        dbpedia-entity  0.499363  0.261577  0.000000  1.000000    400
6         earth_science  0.324640  0.353154  0.000000  1.000000    116
7             economics  0.183037  0.295035  0.000000  1.000000    103
8                 fever  0.917899  0.171437  0.000000  1.000000   6666
9                  fiqa  0.647358  0.328833  0.000000  1.000000    648
10             hotpotqa  0.768152  0.250907  0.000000  1.000000   7405
11             leetcode  0.338177  0.334179  0.000000  1.000000    142
12              msmarco  0.441635  0.376502  0.000000  1.000000   7077
13             nfcorpus  0.413534  0.336107  0.000000  1.000000    323
14                   nq  0.649370  0.347237  0.000000  1.000000   3452
15                 pony  0.009554  0.042976  0.000000  0.358954    112
16           psychology  0.273961  0.331654  0.000000  1.000000    101
17                quora  0.890441  0.223594  0.000000  1.000000  10000
18             robotics  0.159160  0.265726  0.000000  1.000000    101
19              scidocs  0.328168  0.254545  0.000000  1.000000   1000
20              scifact  0.784924  0.318841  0.000000  1.000000    300
21        stackoverflow  0.184461  0.292085  0.000000  1.000000    117
22   sustainable_living  0.175260  0.257138  0.000000  1.000000    108
23  theoremqa_questions  0.390293  0.438044  0.000000  1.000000    194
24   theoremqa_theorems  0.393244  0.386399  0.000000  1.000000     75
25           trec-covid  0.946868  0.091125  0.572884  1.000000     50
26     webis-touche2020  0.357370  0.250975  0.000000  0.962293     49
Processed model: linq
           dataset_name      mean       std       min       max  count
0                  aops  0.081930  0.188776  0.000000  1.000000    111
1               arguana  0.681520  0.322805  0.000000  1.000000   1406
2               biology  0.251507  0.322297  0.000000  1.000000    103
3       browsecomp_plus  0.123965  0.201648  0.000000  0.982892    830
4         climate-fever  0.392794  0.311275  0.000000  1.000000   1535
5        dbpedia-entity  0.512989  0.246993  0.000000  1.000000    400
6         earth_science  0.314442  0.356949  0.000000  1.000000    116
7             economics  0.228876  0.334160  0.000000  1.000000    103
8                 fever  0.923433  0.171814  0.000000  1.000000   6666
9                  fiqa  0.611761  0.366559  0.000000  1.000000    648
10             hotpotqa  0.764488  0.285802  0.000000  1.000000   7405
11             leetcode  0.308948  0.349699  0.000000  1.000000    142
12              msmarco  0.453032  0.380410  0.000000  1.000000   7077
13             nfcorpus  0.418960  0.324198  0.000000  1.000000    323
14                   nq  0.703905  0.328392  0.000000  1.000000   3452
15                 pony  0.237369  0.142123  0.000000  0.585742    112
16           psychology  0.266881  0.335189  0.000000  1.000000    101
17                quora  0.902042  0.209294  0.000000  1.000000  10000
18             robotics  0.183013  0.290021  0.000000  1.000000    101
19              scidocs  0.221109  0.230657  0.000000  1.000000   1000
20              scifact  0.787076  0.322733  0.000000  1.000000    300
21        stackoverflow  0.166265  0.285437  0.000000  1.000000    117
22   sustainable_living  0.248125  0.317696  0.000000  1.000000    108
23  theoremqa_questions  0.288889  0.393204  0.000000  1.000000    194
24   theoremqa_theorems  0.330280  0.346661  0.000000  1.000000     75
25           trec-covid  0.871092  0.161460  0.354079  1.000000     50
26     webis-touche2020  0.299849  0.222961  0.000000  0.945913     49
Processed model: gte
           dataset_name      mean       std       min       max  count
0                  aops  0.157513  0.237478  0.000000  0.932521    111
1               arguana  0.684740  0.315734  0.000000  1.000000   1406
2               biology  0.303235  0.325970  0.000000  1.000000    103
3       browsecomp_plus  0.173875  0.232103  0.000000  1.000000    830
4         climate-fever  0.462452  0.317452  0.000000  1.000000   1535
5        dbpedia-entity  0.523787  0.258103  0.000000  1.000000    400
6         earth_science  0.402998  0.373485  0.000000  1.000000    116
7             economics  0.157534  0.273353  0.000000  1.000000    103
8                 fever  0.951588  0.131099  0.000000  1.000000   6666
9                  fiqa  0.617861  0.349488  0.000000  1.000000    648
10             hotpotqa  0.730239  0.237725  0.000000  1.000000   7405
11             leetcode  0.309736  0.341095  0.000000  1.000000    142
12              msmarco  0.463325  0.379171  0.000000  1.000000   7077
13             nfcorpus  0.399469  0.335477  0.000000  1.000000    323
14                   nq  0.668430  0.340053  0.000000  1.000000   3452
15                 pony  0.024836  0.055282  0.000000  0.298490    112
16           psychology  0.263807  0.335861  0.000000  1.000000    101
17                quora  0.896088  0.216216  0.000000  1.000000  10000
18             robotics  0.124650  0.247257  0.000000  1.000000    101
19              scidocs  0.289023  0.246497  0.000000  1.000000   1000
20              scifact  0.794621  0.304510  0.000000  1.000000    300
21        stackoverflow  0.157799  0.259540  0.000000  1.000000    117
22   sustainable_living  0.209364  0.314064  0.000000  1.000000    108
23  theoremqa_questions  0.321730  0.407170  0.000000  1.000000    194
24   theoremqa_theorems  0.357501  0.350513  0.000000  1.000000     75
25           trec-covid  0.811167  0.167854  0.457675  1.000000     50
26     webis-touche2020  0.338063  0.221711  0.000000  0.924526     49
Processed model: reasonir
           dataset_name      mean       std       min       max  count
0                  aops  0.146281  0.246709  0.000000  1.000000    111
1               arguana  0.602368  0.337997  0.000000  1.000000   1406
2               biology  0.263426  0.301772  0.000000  1.000000    103
3       browsecomp_plus  0.155331  0.218674  0.000000  1.000000    830
4         climate-fever  0.314118  0.297142  0.000000  1.000000   1535
5        dbpedia-entity  0.397478  0.270405  0.000000  1.000000    400
6         earth_science  0.311238  0.346465  0.000000  1.000000    116
7             economics  0.235278  0.343669  0.000000  1.000000    103
8                 fever  0.774458  0.293618  0.000000  1.000000   6666
9                  fiqa  0.483679  0.371010  0.000000  1.000000    648
10             hotpotqa  0.628428  0.323530  0.000000  1.000000   7405
11             leetcode  0.342490  0.371953  0.000000  1.000000    142
12              msmarco  0.326767  0.358579  0.000000  1.000000   7077
13             nfcorpus  0.378909  0.323019  0.000000  1.000000    323
14                   nq  0.526317  0.366438  0.000000  1.000000   3452
15                 pony  0.098917  0.115533  0.000000  0.500866    112
16           psychology  0.301157  0.364256  0.000000  1.000000    101
17                quora  0.810174  0.296093  0.000000  1.000000  10000
18             robotics  0.181897  0.288327  0.000000  1.000000    101
19              scidocs  0.227979  0.232543  0.000000  1.000000   1000
20              scifact  0.751476  0.340442  0.000000  1.000000    300
21        stackoverflow  0.239771  0.332547  0.000000  1.000000    117
22   sustainable_living  0.200860  0.281529  0.000000  1.000000    108
23  theoremqa_questions  0.316701  0.407177  0.000000  1.000000    194
24   theoremqa_theorems  0.278111  0.356342  0.000000  1.000000     75
25           trec-covid  0.768220  0.218656  0.074382  1.000000     50
26     webis-touche2020  0.195552  0.191096  0.000000  0.845023     49
Processed model: diver
           dataset_name      mean       std       min       max  count
0                  aops  0.110621  0.194316  0.000000  1.000000    111
1               arguana  0.482960  0.343998  0.000000  1.000000   1406
2               biology  0.419430  0.343069  0.000000  1.000000    103
3       browsecomp_plus  0.176799  0.226839  0.000000  1.000000    830
4         climate-fever  0.301818  0.288288  0.000000  1.000000   1535
5        dbpedia-entity  0.414853  0.254169  0.000000  1.000000    400
6         earth_science  0.445667  0.356167  0.000000  1.000000    116
7             economics  0.220166  0.316183  0.000000  1.000000    103
8                 fever  0.778438  0.297594  0.000000  1.000000   6666
9                  fiqa  0.478775  0.365834  0.000000  1.000000    648
10             hotpotqa  0.657739  0.291228  0.000000  1.000000   7405
11             leetcode  0.376916  0.372332  0.000000  1.000000    142
12              msmarco  0.318800  0.362590  0.000000  1.000000   7077
13             nfcorpus  0.380451  0.328638  0.000000  1.000000    323
14                   nq  0.542021  0.370257  0.000000  1.000000   3452
15                 pony  0.136139  0.126561  0.000000  0.630863    112
16           psychology  0.344000  0.354838  0.000000  1.000000    101
17                quora  0.883710  0.233417  0.000000  1.000000  10000
18             robotics  0.209036  0.299338  0.000000  1.000000    101
19              scidocs  0.234590  0.237947  0.000000  1.000000   1000
20              scifact  0.764804  0.341277  0.000000  1.000000    300
21        stackoverflow  0.207964  0.280613  0.000000  1.000000    117
22   sustainable_living  0.252973  0.311039  0.000000  1.000000    108
23  theoremqa_questions  0.385281  0.431327  0.000000  1.000000    194
24   theoremqa_theorems  0.367929  0.341302  0.000000  1.000000     75
25           trec-covid  0.788060  0.192564  0.262893  1.000000     50
26     webis-touche2020  0.248296  0.215689  0.000000  0.872167     49
Processed model: bge_reasoner
           dataset_name      mean       std       min       max  count
0                  aops  0.129446  0.210996  0.000000  1.000000    111
1               arguana  0.490272  0.354408  0.000000  1.000000   1406
2               biology  0.532301  0.348379  0.000000  1.000000    103
3       browsecomp_plus  0.160962  0.218187  0.000000  1.000000    830
4         climate-fever  0.252364  0.275823  0.000000  1.000000   1535
5        dbpedia-entity  0.412956  0.256053  0.000000  1.000000    400
6         earth_science  0.563752  0.339115  0.000000  1.000000    116
7             economics  0.355420  0.374063  0.000000  1.000000    103
8                 fever  0.650625  0.373741  0.000000  1.000000   6666
9                  fiqa  0.442301  0.359506  0.000000  1.000000    648
10             hotpotqa  0.444415  0.339227  0.000000  1.000000   7405
11             leetcode  0.341948  0.342896  0.000000  1.000000    142
12              msmarco  0.327308  0.370079  0.000000  1.000000   7077
13             nfcorpus  0.399053  0.335613  0.000000  1.000000    323
14                   nq  0.606713  0.367867  0.000000  1.000000   3452
15                 pony  0.178742  0.181429  0.000000  0.747159    112
16           psychology  0.462373  0.382142  0.000000  1.000000    101
17                quora  0.484936  0.404159  0.000000  1.000000  10000
18             robotics  0.357519  0.373805  0.000000  1.000000    101
19              scidocs  0.225298  0.233720  0.000000  1.000000   1000
20              scifact  0.787951  0.315578  0.000000  1.000000    300
21        stackoverflow  0.367171  0.357170  0.000000  1.000000    117
22   sustainable_living  0.392343  0.353537  0.000000  1.000000    108
23  theoremqa_questions  0.410235  0.439062  0.000000  1.000000    194
24   theoremqa_theorems  0.457557  0.373717  0.000000  1.000000     75
25           trec-covid  0.811631  0.205653  0.116825  1.000000     50
26     webis-touche2020  0.264881  0.225607  0.000000  0.881047     49

In [ ]:
# First, add the task type corresponding to the datasets.
task_types = {
    "msmarco":"Passage Retrieval",
    "trec-covid":"Bio-Medical Retrieval",
    "nfcorpus": "Bio-Medical Retrieval",
    "hotpotqa":"Question Answering",
    "fiqa":"Question Answering",
    "arguana":"Argument Retrieval",
    "quora":"Duplicate Question Retrieval",
    "dbpedia-entity":"Entity Retrieval",
    "scidocs": "Citation-Prediction",
    "nq": "Question Answering",
    "fever":"Fact Checking",
    "climate-fever": "Fact Checking",
    "scifact": "Fact Checking",
    "webis-touche2020":"Argument Retrieval",
    "biology":"StackExchange Post Retrieval",
    "earth_science":"StackExchange Post Retrieval",
    "economics":"StackExchange Post Retrieval",
    "psychology" :"StackExchange Post Retrieval",
    "robotics":"StackExchange Post Retrieval",
    "stackoverflow":"StackExchange Post Retrieval",
    "sustainable_living":"StackExchange Post Retrieval",
    "leetcode":'Code Retrieval',
    "pony":"Code Retrieval",
    "aops" :"Theorem Retrieval",
    "theoremqa_theorems" :"Theorem Retrieval",
    "theoremqa_questions" :"Theorem Retrieval",
    "browsecomp_plus":"Question Answering",
}
# Add a task type column
data['task_type'] = data['dataset_name'].map(task_types)
data

,query_id,dataset_name,raw_query_id,query_type,query_text,split,bm25_score_ndcg@10,contriever_score_ndcg@10,bge_m3_score_ndcg@10,qwen3_score_ndcg@10,linq_score_ndcg@10,gte_score_ndcg@10,reasonir_score_ndcg@10,diver_score_ndcg@10,bge_reasoner_score_ndcg@10,task_type
0,trec-covid__test__1,trec-covid,1,EVIDENCE-BASED,what is the origin of COVID-19,test,0.252841,0.039199,0.340113,1.000000,0.716937,0.784617,0.653408,0.501819,0.778429,Bio-Medical Retrieval
1,trec-covid__test__2,trec-covid,2,EVIDENCE-BASED,how does the coronavirus respond to changes in...,test,0.613283,0.252841,0.864315,1.000000,1.000000,0.861138,0.926636,1.000000,0.921602,Bio-Medical Retrieval
2,trec-covid__test__3,trec-covid,3,DEBATE,will SARS-CoV2 infected people develop immunit...,test,0.195189,0.894275,0.000000,1.000000,0.930569,0.899030,0.827749,0.826422,0.650414,Bio-Medical Retrieval
3,trec-covid__test__4,trec-covid,4,EVIDENCE-BASED,what causes death from Covid-19?,test,0.135685,0.110046,0.314880,1.000000,0.966873,0.965284,0.591945,0.957428,0.831848,Bio-Medical Retrieval
4,trec-covid__test__5,trec-covid,5,EVIDENCE-BASED,what drugs have been active against SARS-CoV o...,test,0.519520,0.508287,0.283713,1.000000,0.743345,0.546287,0.706663,0.671759,0.571936,Bio-Medical Retrieval
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42519,msmarco__test__1132532,msmarco,1132532,FACTOID,average annual income data analyst,test,0.428797,0.835746,0.889954,1.000000,0.978793,0.976856,0.776182,0.770499,0.898255,Passage Retrieval
42520,msmarco__test__1133579,msmarco,1133579,EVIDENCE-BASED,how does granulation tissue start,test,0.554417,0.629336,0.812214,0.818852,0.817511,0.627877,0.652478,0.676379,0.741429,Passage Retrieval
42521,msmarco__test__1136043,msmarco,1136043,FACTOID,difference between a hotel and motel,test,0.346317,0.805447,0.724774,0.725397,0.724774,0.723278,0.618023,0.683002,0.593403,Passage Retrieval
42522,msmarco__test__1136047,msmarco,1136047,FACTOID,difference between a company's strategy and bu...,test,0.459095,0.327582,0.475790,0.557774,0.613942,0.371733,0.433620,0.461970,0.305609,Passage Retrieval
42523,msmarco__test__1136962,msmarco,1136962,REASON,why did the ancient egyptians call their land ...,test,0.736643,0.693325,0.926636,0.814791,0.848238,0.865011,0.881292,0.880349,0.863444,Passage Retrieval

In [ ]:
# 2, Statistical Analysis

# Perform statistical analysis on the performance of each model on each specific task, calculate the mean and standard deviation of ndcg@10, and calculate the average performance at the task level.
 

task_list = ['Passage Retrieval','Bio-Medical Retrieval','Question Answering','Duplicate Question Retrieval','Entity Retrieval','Citation-Prediction', 'Fact Checking', \
 'Argument Retrieval','StackExchange Post Retrieval', 'Code Retrieval', 'Theorem Retrieval', ]


for model in model_name_list:
    col = f"{model}_score_ndcg@10"
    grouped_task = data.groupby(['task_type'])[col].agg(
        ['mean', 'std', 'min', 'max', 'count']).reset_index()
    # Add model column to grouped_task
    grouped_task['model'] = model
    
    # Calculate the average task-level performance.
    overall_mean = grouped_task['mean'].mean()
    print(f"Processed model: {model}")
    # print(grouped_task)
    print(f"Task-Level Overall Mean for model {model}: {overall_mean}")

    # Add a row to calculate statistics for all queries.
    overall_stats = data[col].agg(['mean', 'std', 'min', 'max', 'count']).to_frame().T
    overall_stats['task_type'] = 'ALL-query-level'
    overall_stats['model'] = model
    grouped_task = pd.concat([grouped_task, overall_stats], ignore_index=True)

    # Reorder the rows according to the query_type_list, while retaining the newly added 'ALL' rows.
    grouped_task = grouped_task.set_index('task_type').reindex(task_list + ['ALL-query-level']).reset_index()

    print(f"Model: {model} - Task Type Performance:")
    print(grouped_task)
    print("-" * 50)

Processed model: bm25
Task-Level Overall Mean for model bm25: 0.325671651752591
Model: bm25 - Task Type Performance:
                       task_type      mean       std  min  max    count model
0              Passage Retrieval  0.221301  0.326066  0.0  1.0   7077.0  bm25
1          Bio-Medical Retrieval  0.342846  0.321427  0.0  1.0    373.0  bm25
2             Question Answering  0.458546  0.349367  0.0  1.0  12335.0  bm25
3   Duplicate Question Retrieval  0.769127  0.327340  0.0  1.0  10000.0  bm25
4               Entity Retrieval  0.309808  0.269749  0.0  1.0    400.0  bm25
5            Citation-Prediction  0.144143  0.203627  0.0  1.0   1000.0  bm25
6                  Fact Checking  0.523770  0.402584  0.0  1.0   8501.0  bm25
7             Argument Retrieval  0.388526  0.348664  0.0  1.0   1455.0  bm25
8   StackExchange Post Retrieval  0.174144  0.272762  0.0  1.0    749.0  bm25
9                 Code Retrieval  0.169408  0.275190  0.0  1.0    254.0  bm25
10             Theorem Retrieval  0.080770  0.215481  0.0  1.0    380.0  bm25
11               ALL-query-level  0.482823  0.397378  0.0  1.0  42524.0  bm25
--------------------------------------------------
Processed model: contriever
Task-Level Overall Mean for model contriever: 0.390228770889882
Model: contriever - Task Type Performance:
                       task_type      mean       std  min  max    count  \
0              Passage Retrieval  0.410740  0.376010  0.0  1.0   7077.0
1          Bio-Medical Retrieval  0.363514  0.325092  0.0  1.0    373.0
2             Question Answering  0.544139  0.339976  0.0  1.0  12335.0
3   Duplicate Question Retrieval  0.864355  0.249906  0.0  1.0  10000.0
4               Entity Retrieval  0.413144  0.271565  0.0  1.0    400.0
5            Citation-Prediction  0.165929  0.211642  0.0  1.0   1000.0
6                  Fact Checking  0.660786  0.370055  0.0  1.0   8501.0
7             Argument Retrieval  0.437305  0.351643  0.0  1.0   1455.0
8   StackExchange Post Retrieval  0.177618  0.279764  0.0  1.0    749.0
9                 Code Retrieval  0.167013  0.265931  0.0  1.0    254.0
10             Theorem Retrieval  0.087974  0.235255  0.0  1.0    380.0
11               ALL-query-level  0.592409  0.380843  0.0  1.0  42524.0

         model
0   contriever
1   contriever
2   contriever
3   contriever
4   contriever
5   contriever
6   contriever
7   contriever
8   contriever
9   contriever
10  contriever
11  contriever
--------------------------------------------------
Processed model: bge_m3
Task-Level Overall Mean for model bge_m3: 0.4044646192842267
Model: bge_m3 - Task Type Performance:
                       task_type      mean       std  min       max    count  \
0              Passage Retrieval  0.387654  0.378451  0.0  1.000000   7077.0
1          Bio-Medical Retrieval  0.348503  0.317391  0.0  1.000000    373.0
2             Question Answering  0.612456  0.347431  0.0  1.000000  12335.0
3   Duplicate Question Retrieval  0.885569  0.229957  0.0  1.000000  10000.0
4               Entity Retrieval  0.398264  0.259022  0.0  1.000000    400.0
5            Citation-Prediction  0.164188  0.207468  0.0  0.989606   1000.0
6                  Fact Checking  0.710703  0.347365  0.0  1.000000   8501.0
7             Argument Retrieval  0.529404  0.351556  0.0  1.000000   1455.0
8   StackExchange Post Retrieval  0.120027  0.231754  0.0  1.000000    749.0
9                 Code Retrieval  0.203198  0.278238  0.0  1.000000    254.0
10             Theorem Retrieval  0.089145  0.241661  0.0  1.000000    380.0
11               ALL-query-level  0.625402  0.381458  0.0  1.000000  42524.0

     model
0   bge_m3
1   bge_m3
2   bge_m3
3   bge_m3
4   bge_m3
5   bge_m3
6   bge_m3
7   bge_m3
8   bge_m3
9   bge_m3
10  bge_m3
11  bge_m3
--------------------------------------------------
Processed model: qwen3
Task-Level Overall Mean for model qwen3: 0.5121896902941832
Model: qwen3 - Task Type Performance:
                       task_type      mean       std  min  max    count  model
0              Passage Retrieval  0.441635  0.376502  0.0  1.0   7077.0  qwen3
1          Bio-Medical Retrieval  0.485027  0.363297  0.0  1.0    373.0  qwen3
2             Question Answering  0.690334  0.318785  0.0  1.0  12335.0  qwen3
3   Duplicate Question Retrieval  0.890441  0.223594  0.0  1.0  10000.0  qwen3
4               Entity Retrieval  0.499363  0.261577  0.0  1.0    400.0  qwen3
5            Citation-Prediction  0.328168  0.254545  0.0  1.0   1000.0  qwen3
6                  Fact Checking  0.833011  0.271823  0.0  1.0   8501.0  qwen3
7             Argument Retrieval  0.752585  0.290670  0.0  1.0   1455.0  qwen3
8   StackExchange Post Retrieval  0.215089  0.301732  0.0  1.0    749.0  qwen3
9                 Code Retrieval  0.193272  0.299626  0.0  1.0    254.0  qwen3
10             Theorem Retrieval  0.305163  0.393392  0.0  1.0    380.0  qwen3
11               ALL-query-level  0.699759  0.351730  0.0  1.0  42524.0  qwen3
--------------------------------------------------
Processed model: linq
Task-Level Overall Mean for model linq: 0.5007079176011296
Model: linq - Task Type Performance:
                       task_type      mean       std  min  max    count model
0              Passage Retrieval  0.453032  0.380410  0.0  1.0   7077.0  linq
1          Bio-Medical Retrieval  0.479568  0.343808  0.0  1.0    373.0  linq
2             Question Answering  0.696411  0.337957  0.0  1.0  12335.0  linq
3   Duplicate Question Retrieval  0.902042  0.209294  0.0  1.0  10000.0  linq
4               Entity Retrieval  0.512989  0.246993  0.0  1.0    400.0  linq
5            Citation-Prediction  0.221109  0.230657  0.0  1.0   1000.0  linq
6                  Fact Checking  0.822805  0.292704  0.0  1.0   8501.0  linq
7             Argument Retrieval  0.668666  0.327226  0.0  1.0   1455.0  linq
8   StackExchange Post Retrieval  0.237176  0.323421  0.0  1.0    749.0  linq
9                 Code Retrieval  0.277386  0.279792  0.0  1.0    254.0  linq
10             Theorem Retrieval  0.236604  0.350260  0.0  1.0    380.0  linq
11               ALL-query-level  0.699076  0.360918  0.0  1.0  42524.0  linq
--------------------------------------------------
Processed model: gte
Task-Level Overall Mean for model gte: 0.502290937194447
Model: gte - Task Type Performance:
                       task_type      mean       std  min  max    count model
0              Passage Retrieval  0.463325  0.379171  0.0  1.0   7077.0   gte
1          Bio-Medical Retrieval  0.454656  0.347645  0.0  1.0    373.0   gte
2             Question Answering  0.669601  0.308533  0.0  1.0  12335.0   gte
3   Duplicate Question Retrieval  0.896088  0.216216  0.0  1.0  10000.0   gte
4               Entity Retrieval  0.523787  0.258103  0.0  1.0    400.0   gte
5            Citation-Prediction  0.289023  0.246497  0.0  1.0   1000.0   gte
6                  Fact Checking  0.857726  0.264935  0.0  1.0   8501.0   gte
7             Argument Retrieval  0.673065  0.319163  0.0  1.0   1455.0   gte
8   StackExchange Post Retrieval  0.232997  0.320247  0.0  1.0    749.0   gte
9                 Code Retrieval  0.184111  0.293717  0.0  1.0    254.0   gte
10             Theorem Retrieval  0.280821  0.362291  0.0  1.0    380.0   gte
11               ALL-query-level  0.699989  0.349375  0.0  1.0  42524.0   gte
--------------------------------------------------
Processed model: reasonir
Task-Level Overall Mean for model reasonir: 0.43416619088733577
Model: reasonir - Task Type Performance:
                       task_type      mean       std  min  max    count  \
0              Passage Retrieval  0.326767  0.358579  0.0  1.0   7077.0
1          Bio-Medical Retrieval  0.431095  0.338017  0.0  1.0    373.0
2             Question Answering  0.560414  0.353967  0.0  1.0  12335.0
3   Duplicate Question Retrieval  0.810174  0.296093  0.0  1.0  10000.0
4               Entity Retrieval  0.397478  0.270405  0.0  1.0    400.0
5            Citation-Prediction  0.227979  0.232543  0.0  1.0   1000.0
6                  Fact Checking  0.690525  0.344751  0.0  1.0   8501.0
7             Argument Retrieval  0.588668  0.342034  0.0  1.0   1455.0
8   StackExchange Post Retrieval  0.248337  0.326032  0.0  1.0    749.0
9                 Code Retrieval  0.235087  0.312478  0.0  1.0    254.0
10             Theorem Retrieval  0.259304  0.363845  0.0  1.0    380.0
11               ALL-query-level  0.586625  0.381223  0.0  1.0  42524.0

       model
0   reasonir
1   reasonir
2   reasonir
3   reasonir
4   reasonir
5   reasonir
6   reasonir
7   reasonir
8   reasonir
9   reasonir
10  reasonir
11  reasonir
--------------------------------------------------
Processed model: diver
Task-Level Overall Mean for model diver: 0.44640674650464907
Model: diver - Task Type Performance:
                       task_type      mean       std  min  max    count  model
0              Passage Retrieval  0.318800  0.362590  0.0  1.0   7077.0  diver
1          Bio-Medical Retrieval  0.435090  0.343087  0.0  1.0    373.0  diver
2             Question Answering  0.583591  0.339480  0.0  1.0  12335.0  diver
3   Duplicate Question Retrieval  0.883710  0.233417  0.0  1.0  10000.0  diver
4               Entity Retrieval  0.414853  0.254169  0.0  1.0    400.0  diver
5            Citation-Prediction  0.234590  0.237947  0.0  1.0   1000.0  diver
6                  Fact Checking  0.691895  0.349397  0.0  1.0   8501.0  diver
7             Argument Retrieval  0.475057  0.343039  0.0  1.0   1455.0  diver
8   StackExchange Post Retrieval  0.300515  0.336457  0.0  1.0    749.0  diver
9                 Code Retrieval  0.270747  0.314064  0.0  1.0    254.0  diver
10             Theorem Retrieval  0.301627  0.378919  0.0  1.0    380.0  diver
11               ALL-query-level  0.607566  0.380030  0.0  1.0  42524.0  diver
--------------------------------------------------
Processed model: bge_reasoner
Task-Level Overall Mean for model bge_reasoner: 0.4075599122382135
Model: bge_reasoner - Task Type Performance:
                       task_type      mean       std  min  max    count  \
0              Passage Retrieval  0.327308  0.370079  0.0  1.0   7077.0
1          Bio-Medical Retrieval  0.454358  0.350542  0.0  1.0    373.0
2             Question Answering  0.470651  0.359183  0.0  1.0  12335.0
3   Duplicate Question Retrieval  0.484936  0.404159  0.0  1.0  10000.0
4               Entity Retrieval  0.412956  0.256053  0.0  1.0    400.0
5            Citation-Prediction  0.225298  0.233720  0.0  1.0   1000.0
6                  Fact Checking  0.583558  0.389322  0.0  1.0   8501.0
7             Argument Retrieval  0.482682  0.353138  0.0  1.0   1455.0
8   StackExchange Post Retrieval  0.433874  0.368533  0.0  1.0    749.0
9                 Code Retrieval  0.269983  0.294213  0.0  1.0    254.0
10             Theorem Retrieval  0.337555  0.395723  0.0  1.0    380.0
11               ALL-query-level  0.463646  0.385097  0.0  1.0  42524.0

           model
0   bge_reasoner
1   bge_reasoner
2   bge_reasoner
3   bge_reasoner
4   bge_reasoner
5   bge_reasoner
6   bge_reasoner
7   bge_reasoner
8   bge_reasoner
9   bge_reasoner
10  bge_reasoner
11  bge_reasoner
--------------------------------------------------

In [ ]:
# Performance statistics based on query type
 

query_type_list = ["FACTOID", "INSTRUCTION", "REASON", "EVIDENCE-BASED", "COMPARISON", "EXPERIENCE", "DEBATE",
                   "NOT-A-QUESTION"]

for model in model_name_list:
    col = f"{model}_score_ndcg@10"
    grouped_query_type = data.groupby(['query_type'])[col].agg(
        ['mean', 'std', 'min', 'max', 'count']).reset_index()
    grouped_query_type['model'] = model

        # Calculate the average performance of query_type-level
    overall_mean = grouped_query_type['mean'].mean()
    print(f"Query Type-Level Overall Mean for model {model}: {overall_mean}")
    #Add a row to calculate statistics for all queries.
    overall_stats = data[col].agg(['mean', 'std', 'min', 'max', 'count']).to_frame().T
    overall_stats['query_type'] = 'ALL-query-level'
    overall_stats['model'] = model
    grouped_query_type = pd.concat([grouped_query_type, overall_stats], ignore_index=True)

    # Reorder the rows according to the query_type_list, while retaining the newly added 'ALL' rows.
    grouped_query_type = grouped_query_type.set_index('query_type').reindex(query_type_list + ['ALL-query-level']).reset_index()

    print(f"Model: {model} - Query Type Performance:")
    print(grouped_query_type)
    print("-" * 50)

Query Type-Level Overall Mean for model bm25: 0.5819432443997767
Model: bm25 - Query Type Performance:
        query_type      mean       std  min  max    count model
0          FACTOID  0.425245  0.362206  0.0  1.0  15887.0  bm25
1      INSTRUCTION  0.627936  0.397576  0.0  1.0   2708.0  bm25
2           REASON  0.639736  0.403266  0.0  1.0   1381.0  bm25
3   EVIDENCE-BASED  0.397188  0.417291  0.0  1.0   5589.0  bm25
4       COMPARISON  0.703788  0.346235  0.0  1.0    539.0  bm25
5       EXPERIENCE  0.737081  0.345452  0.0  1.0   1582.0  bm25
6           DEBATE  0.672417  0.364307  0.0  1.0   3257.0  bm25
7   NOT-A-QUESTION  0.452155  0.402790  0.0  1.0  11581.0  bm25
8  ALL-query-level  0.482823  0.397378  0.0  1.0  42524.0  bm25
--------------------------------------------------
Query Type-Level Overall Mean for model contriever: 0.6899849921767358
Model: contriever - Query Type Performance:
        query_type      mean       std  min  max    count       model
0          FACTOID  0.525492  0.351842  0.0  1.0  15887.0  contriever
1      INSTRUCTION  0.724390  0.361372  0.0  1.0   2708.0  contriever
2           REASON  0.733302  0.363343  0.0  1.0   1381.0  contriever
3   EVIDENCE-BASED  0.558178  0.405385  0.0  1.0   5589.0  contriever
4       COMPARISON  0.815647  0.282671  0.0  1.0    539.0  contriever
5       EXPERIENCE  0.840431  0.272625  0.0  1.0   1582.0  contriever
6           DEBATE  0.761084  0.334029  0.0  1.0   3257.0  contriever
7   NOT-A-QUESTION  0.561357  0.398937  0.0  1.0  11581.0  contriever
8  ALL-query-level  0.592409  0.380843  0.0  1.0  42524.0  contriever
--------------------------------------------------
Query Type-Level Overall Mean for model bge_m3: 0.718818740337367
Model: bge_m3 - Query Type Performance:
        query_type      mean       std  min  max    count   model
0          FACTOID  0.563383  0.363960  0.0  1.0  15887.0  bge_m3
1      INSTRUCTION  0.749601  0.355718  0.0  1.0   2708.0  bge_m3
2           REASON  0.753332  0.361760  0.0  1.0   1381.0  bge_m3
3   EVIDENCE-BASED  0.560373  0.410554  0.0  1.0   5589.0  bge_m3
4       COMPARISON  0.858929  0.262445  0.0  1.0    539.0  bge_m3
5       EXPERIENCE  0.868254  0.256101  0.0  1.0   1582.0  bge_m3
6           DEBATE  0.789226  0.323121  0.0  1.0   3257.0  bge_m3
7   NOT-A-QUESTION  0.607451  0.391454  0.0  1.0  11581.0  bge_m3
8  ALL-query-level  0.625402  0.381458  0.0  1.0  42524.0  bge_m3
--------------------------------------------------
Query Type-Level Overall Mean for model qwen3: 0.7652731759546396
Model: qwen3 - Query Type Performance:
        query_type      mean       std  min  max    count  model
0          FACTOID  0.633230  0.344462  0.0  1.0  15887.0  qwen3
1      INSTRUCTION  0.774363  0.328995  0.0  1.0   2708.0  qwen3
2           REASON  0.782151  0.336644  0.0  1.0   1381.0  qwen3
3   EVIDENCE-BASED  0.606163  0.392276  0.0  1.0   5589.0  qwen3
4       COMPARISON  0.886628  0.233227  0.0  1.0    539.0  qwen3
5       EXPERIENCE  0.871524  0.242602  0.0  1.0   1582.0  qwen3
6           DEBATE  0.827205  0.293278  0.0  1.0   3257.0  qwen3
7   NOT-A-QUESTION  0.740921  0.345506  0.0  1.0  11581.0  qwen3
8  ALL-query-level  0.699759  0.351730  0.0  1.0  42524.0  qwen3
--------------------------------------------------
Query Type-Level Overall Mean for model linq: 0.7707904195124586
Model: linq - Query Type Performance:
        query_type      mean       std  min  max    count model
0          FACTOID  0.639069  0.357838  0.0  1.0  15887.0  linq
1      INSTRUCTION  0.784042  0.327253  0.0  1.0   2708.0  linq
2           REASON  0.798187  0.328584  0.0  1.0   1381.0  linq
3   EVIDENCE-BASED  0.613322  0.395224  0.0  1.0   5589.0  linq
4       COMPARISON  0.893027  0.238176  0.0  1.0    539.0  linq
5       EXPERIENCE  0.887521  0.228831  0.0  1.0   1582.0  linq
6           DEBATE  0.832296  0.288570  0.0  1.0   3257.0  linq
7   NOT-A-QUESTION  0.718859  0.364501  0.0  1.0  11581.0  linq
8  ALL-query-level  0.699076  0.360918  0.0  1.0  42524.0  linq
--------------------------------------------------
Query Type-Level Overall Mean for model gte: 0.7673447671373719
Model: gte - Query Type Performance:
        query_type      mean       std  min  max    count model
0          FACTOID  0.624629  0.332735  0.0  1.0  15887.0   gte
1      INSTRUCTION  0.784079  0.326542  0.0  1.0   2708.0   gte
2           REASON  0.786817  0.329500  0.0  1.0   1381.0   gte
3   EVIDENCE-BASED  0.617570  0.391111  0.0  1.0   5589.0   gte
4       COMPARISON  0.876131  0.235927  0.0  1.0    539.0   gte
5       EXPERIENCE  0.880257  0.232449  0.0  1.0   1582.0   gte
6           DEBATE  0.823789  0.289083  0.0  1.0   3257.0   gte
7   NOT-A-QUESTION  0.745486  0.354005  0.0  1.0  11581.0   gte
8  ALL-query-level  0.699989  0.349375  0.0  1.0  42524.0   gte
--------------------------------------------------
Query Type-Level Overall Mean for model reasonir: 0.6665131832481273
Model: reasonir - Query Type Performance:
        query_type      mean       std  min  max    count     model
0          FACTOID  0.508572  0.367905  0.0  1.0  15887.0  reasonir
1      INSTRUCTION  0.674388  0.371151  0.0  1.0   2708.0  reasonir
2           REASON  0.728671  0.367201  0.0  1.0   1381.0  reasonir
3   EVIDENCE-BASED  0.518201  0.409332  0.0  1.0   5589.0  reasonir
4       COMPARISON  0.783544  0.300054  0.0  1.0    539.0  reasonir
5       EXPERIENCE  0.772409  0.321233  0.0  1.0   1582.0  reasonir
6           DEBATE  0.732677  0.339136  0.0  1.0   3257.0  reasonir
7   NOT-A-QUESTION  0.613643  0.374400  0.0  1.0  11581.0  reasonir
8  ALL-query-level  0.586625  0.381223  0.0  1.0  42524.0  reasonir
--------------------------------------------------
Query Type-Level Overall Mean for model diver: 0.7069598353315472
Model: diver - Query Type Performance:
        query_type      mean       std  min  max    count  model
0          FACTOID  0.531152  0.362431  0.0  1.0  15887.0  diver
1      INSTRUCTION  0.754003  0.345221  0.0  1.0   2708.0  diver
2           REASON  0.767757  0.351370  0.0  1.0   1381.0  diver
3   EVIDENCE-BASED  0.521460  0.419218  0.0  1.0   5589.0  diver
4       COMPARISON  0.823393  0.271234  0.0  1.0    539.0  diver
5       EXPERIENCE  0.866762  0.257707  0.0  1.0   1582.0  diver
6           DEBATE  0.786254  0.313796  0.0  1.0   3257.0  diver
7   NOT-A-QUESTION  0.604898  0.377606  0.0  1.0  11581.0  diver
8  ALL-query-level  0.607566  0.380030  0.0  1.0  42524.0  diver
--------------------------------------------------
Query Type-Level Overall Mean for model bge_reasoner: 0.4739624038910768
Model: bge_reasoner - Query Type Performance:
        query_type      mean       std  min  max    count         model
0          FACTOID  0.442472  0.368180  0.0  1.0  15887.0  bge_reasoner
1      INSTRUCTION  0.368714  0.385478  0.0  1.0   2708.0  bge_reasoner
2           REASON  0.501866  0.401790  0.0  1.0   1381.0  bge_reasoner
3   EVIDENCE-BASED  0.384817  0.383293  0.0  1.0   5589.0  bge_reasoner
4       COMPARISON  0.595850  0.368078  0.0  1.0    539.0  bge_reasoner
5       EXPERIENCE  0.445934  0.396828  0.0  1.0   1582.0  bge_reasoner
6           DEBATE  0.524524  0.383778  0.0  1.0   3257.0  bge_reasoner
7   NOT-A-QUESTION  0.527523  0.390716  0.0  1.0  11581.0  bge_reasoner
8  ALL-query-level  0.463646  0.385097  0.0  1.0  42524.0  bge_reasoner
--------------------------------------------------

In [ ]:
# Separate the datasets by corpus source type and compute the performance statistics for each corpus category
corpus_types = {
    "msmarco":"General Web",
    "trec-covid":"Scientific Paper",
    "nfcorpus": "Scientific Paper",
    "nq": "Wikipedia",
    "hotpotqa":"Wikipedia",
    "fiqa":"Online Community",
    "quora":"Online Community",
    "dbpedia-entity":"Wikipedia",
    "scidocs": "Scientific Paper",
    "scifact": "Scientific Paper",
    "fever":"Wikipedia",
    "climate-fever": "Wikipedia",
    "arguana":"Domain KB",
    "webis-touche2020":"Domain KB",
    "biology":"Online Community",
    "earth_science":"Online Community",
    "economics":"Online Community",
    "psychology" :"Online Community",
    "robotics":"Online Community",
    "stackoverflow":"Online Community",
    "sustainable_living":"Online Community",
    "leetcode":'Domain KB',
    "pony":"Domain KB",
    "aops" :"Domain KB",
    "theoremqa_theorems" :"Domain KB",
    "theoremqa_questions" :"Domain KB",
    "browsecomp_plus":"General Web",
}

corpus_types_list = ["General Web", "Scientific Paper", "Wikipedia", "Online Community",  "Domain KB", ]

# Add a corpus_type column
data['corpus_type'] = data['dataset_name'].map(corpus_types)
data

,query_id,dataset_name,raw_query_id,query_type,query_text,split,bm25_score_ndcg@10,contriever_score_ndcg@10,bge_m3_score_ndcg@10,qwen3_score_ndcg@10,linq_score_ndcg@10,gte_score_ndcg@10,reasonir_score_ndcg@10,diver_score_ndcg@10,bge_reasoner_score_ndcg@10,task_type,corpus_type
0,trec-covid__test__1,trec-covid,1,EVIDENCE-BASED,what is the origin of COVID-19,test,0.252841,0.039199,0.340113,1.000000,0.716937,0.784617,0.653408,0.501819,0.778429,Bio-Medical Retrieval,Scientific Paper
1,trec-covid__test__2,trec-covid,2,EVIDENCE-BASED,how does the coronavirus respond to changes in...,test,0.613283,0.252841,0.864315,1.000000,1.000000,0.861138,0.926636,1.000000,0.921602,Bio-Medical Retrieval,Scientific Paper
2,trec-covid__test__3,trec-covid,3,DEBATE,will SARS-CoV2 infected people develop immunit...,test,0.195189,0.894275,0.000000,1.000000,0.930569,0.899030,0.827749,0.826422,0.650414,Bio-Medical Retrieval,Scientific Paper
3,trec-covid__test__4,trec-covid,4,EVIDENCE-BASED,what causes death from Covid-19?,test,0.135685,0.110046,0.314880,1.000000,0.966873,0.965284,0.591945,0.957428,0.831848,Bio-Medical Retrieval,Scientific Paper
4,trec-covid__test__5,trec-covid,5,EVIDENCE-BASED,what drugs have been active against SARS-CoV o...,test,0.519520,0.508287,0.283713,1.000000,0.743345,0.546287,0.706663,0.671759,0.571936,Bio-Medical Retrieval,Scientific Paper
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42519,msmarco__test__1132532,msmarco,1132532,FACTOID,average annual income data analyst,test,0.428797,0.835746,0.889954,1.000000,0.978793,0.976856,0.776182,0.770499,0.898255,Passage Retrieval,General Web
42520,msmarco__test__1133579,msmarco,1133579,EVIDENCE-BASED,how does granulation tissue start,test,0.554417,0.629336,0.812214,0.818852,0.817511,0.627877,0.652478,0.676379,0.741429,Passage Retrieval,General Web
42521,msmarco__test__1136043,msmarco,1136043,FACTOID,difference between a hotel and motel,test,0.346317,0.805447,0.724774,0.725397,0.724774,0.723278,0.618023,0.683002,0.593403,Passage Retrieval,General Web
42522,msmarco__test__1136047,msmarco,1136047,FACTOID,difference between a company's strategy and bu...,test,0.459095,0.327582,0.475790,0.557774,0.613942,0.371733,0.433620,0.461970,0.305609,Passage Retrieval,General Web
42523,msmarco__test__1136962,msmarco,1136962,REASON,why did the ancient egyptians call their land ...,test,0.736643,0.693325,0.926636,0.814791,0.848238,0.865011,0.881292,0.880349,0.863444,Passage Retrieval,General Web

In [ ]:
for model in model_name_list:
    col = f"{model}_score_ndcg@10"
    grouped_corpus_type = data.groupby(['corpus_type'])[col].agg(
        ['mean', 'std', 'min', 'max', 'count']).reset_index()
    grouped_corpus_type['model'] = model

        # # Calculate the average performance of corpus_type-level
    overall_mean = grouped_corpus_type['mean'].mean()
    print(f"Task-Level Overall Mean for model {model}: {overall_mean}")
 
    overall_stats = data[col].agg(['mean', 'std', 'min', 'max', 'count']).to_frame().T
    overall_stats['corpus_type'] = 'ALL-query-level'
    overall_stats['model'] = model
    grouped_corpus_type = pd.concat([grouped_corpus_type, overall_stats], ignore_index=True)

    # Reorder the rows according to the order of courpus_type_list, while retaining the newly added 'ALL' rows.
    grouped_corpus_type = grouped_corpus_type.set_index('corpus_type').reindex(corpus_types_list + ['ALL-query-level']).reset_index()

    print(f"Model: {model} - corpus_type Type Performance:")
    print(grouped_corpus_type)
    print("-" * 50)

Task-Level Overall Mean for model bm25: 0.3993991529807195
Model: bm25 - corpus_type Type Performance:
        corpus_type      mean       std  min  max    count model
0       General Web  0.202677  0.315625  0.0  1.0   7907.0  bm25
1  Scientific Paper  0.282876  0.335903  0.0  1.0   1673.0  bm25
2         Wikipedia  0.505786  0.365872  0.0  1.0  19458.0  bm25
3  Online Community  0.699755  0.373187  0.0  1.0  11397.0  bm25
4         Domain KB  0.305902  0.344247  0.0  1.0   2089.0  bm25
5   ALL-query-level  0.482823  0.397378  0.0  1.0  42524.0  bm25
--------------------------------------------------
Task-Level Overall Mean for model contriever: 0.4847872058944619
Model: contriever - corpus_type Type Performance:
        corpus_type      mean       std  min  max    count       model
0       General Web  0.374858  0.374119  0.0  1.0   7907.0  contriever
1  Scientific Paper  0.301566  0.338314  0.0  1.0   1673.0  contriever
2         Wikipedia  0.617755  0.341853  0.0  1.0  19458.0  contriever
3  Online Community  0.788862  0.328723  0.0  1.0  11397.0  contriever
4         Domain KB  0.340895  0.355695  0.0  1.0   2089.0  contriever
5   ALL-query-level  0.592409  0.380843  0.0  1.0  42524.0  contriever
--------------------------------------------------
Task-Level Overall Mean for model bge_m3: 0.508602657971956
Model: bge_m3 - corpus_type Type Performance:
        corpus_type      mean       std  min  max    count   model
0       General Web  0.353568  0.374601  0.0  1.0   7907.0  bge_m3
1  Scientific Paper  0.290842  0.329965  0.0  1.0   1673.0  bge_m3
2         Wikipedia  0.680692  0.330361  0.0  1.0  19458.0  bge_m3
3  Online Community  0.808255  0.320568  0.0  1.0  11397.0  bge_m3
4         Domain KB  0.409656  0.374057  0.0  1.0   2089.0  bge_m3
5   ALL-query-level  0.625402  0.381458  0.0  1.0  42524.0  bge_m3
--------------------------------------------------
Task-Level Overall Mean for model qwen3: 0.6132743420511575
Model: qwen3 - corpus_type Type Performance:
        corpus_type      mean       std  min  max    count  model
0       General Web  0.416269  0.372378  0.0  1.0   7907.0  qwen3
1  Scientific Paper  0.445045  0.339869  0.0  1.0   1673.0  qwen3
2         Wikipedia  0.769631  0.288585  0.0  1.0  19458.0  qwen3
3  Online Community  0.832236  0.293137  0.0  1.0  11397.0  qwen3
4         Domain KB  0.603190  0.387248  0.0  1.0   2089.0  qwen3
5   ALL-query-level  0.699759  0.351730  0.0  1.0  42524.0  qwen3
--------------------------------------------------
Task-Level Overall Mean for model linq: 0.5913500262265676
Model: linq - corpus_type Type Performance:
        corpus_type      mean       std  min  max    count model
0       General Web  0.418489  0.379418  0.0  1.0   7907.0  linq
1  Scientific Paper  0.380221  0.351791  0.0  1.0   1673.0  linq
2         Wikipedia  0.773700  0.301055  0.0  1.0  19458.0  linq
3  Online Community  0.841843  0.288356  0.0  1.0  11397.0  linq
4         Domain KB  0.542496  0.378140  0.0  1.0   2089.0  linq
5   ALL-query-level  0.699076  0.360918  0.0  1.0  42524.0  linq
--------------------------------------------------
Task-Level Overall Mean for model gte: 0.5996487674271641
Model: gte - corpus_type Type Performance:
        corpus_type      mean       std  min  max    count model
0       General Web  0.432942  0.377092  0.0  1.0   7907.0   gte
1  Scientific Paper  0.416615  0.339813  0.0  1.0   1673.0   gte
2         Wikipedia  0.769735  0.282225  0.0  1.0  19458.0   gte
3  Online Community  0.836691  0.290614  0.0  1.0  11397.0   gte
4         Domain KB  0.542262  0.381022  0.0  1.0   2089.0   gte
5   ALL-query-level  0.699989  0.349375  0.0  1.0  42524.0   gte
--------------------------------------------------
Task-Level Overall Mean for model reasonir: 0.509431171936283
Model: reasonir - corpus_type Type Performance:
        corpus_type      mean       std  min  max    count     model
0       General Web  0.308772  0.350508  0.0  1.0   7907.0  reasonir
1  Scientific Paper  0.367137  0.342717  0.0  1.0   1673.0  reasonir
2         Wikipedia  0.630797  0.345948  0.0  1.0  19458.0  reasonir
3  Online Community  0.754687  0.339772  0.0  1.0  11397.0  reasonir
4         Domain KB  0.485763  0.376407  0.0  1.0   2089.0  reasonir
5   ALL-query-level  0.586625  0.381223  0.0  1.0  42524.0  reasonir
--------------------------------------------------
Task-Level Overall Mean for model diver: 0.5129556226150981
Model: diver - corpus_type Type Performance:
        corpus_type      mean       std  min  max    count  model
0       General Web  0.303894  0.353496  0.0  1.0   7907.0  diver
1  Scientific Paper  0.374369  0.347427  0.0  1.0   1673.0  diver
2         Wikipedia  0.645488  0.336492  0.0  1.0  19458.0  diver
3  Online Community  0.822360  0.301242  0.0  1.0  11397.0  diver
4         Domain KB  0.418667  0.356831  0.0  1.0   2089.0  diver
5   ALL-query-level  0.607566  0.380030  0.0  1.0  42524.0  diver
--------------------------------------------------
Task-Level Overall Mean for model bge_reasoner: 0.4249479530747829
Model: bge_reasoner - corpus_type Type Performance:
        corpus_type      mean       std  min  max    count         model
0       General Web  0.309846  0.360793  0.0  1.0   7907.0  bge_reasoner
1  Scientific Paper  0.377262  0.350980  0.0  1.0   1673.0  bge_reasoner
2         Wikipedia  0.528055  0.371697  0.0  1.0  19458.0  bge_reasoner
3  Online Community  0.479156  0.399768  0.0  1.0  11397.0  bge_reasoner
4         Domain KB  0.430421  0.363810  0.0  1.0   2089.0  bge_reasoner
5   ALL-query-level  0.463646  0.385097  0.0  1.0  42524.0  bge_reasoner
--------------------------------------------------

In [9]:
data

,query_id,dataset_name,raw_query_id,query_type,query_text,split,bm25_score_ndcg@10,contriever_score_ndcg@10,bge_m3_score_ndcg@10,qwen3_score_ndcg@10,linq_score_ndcg@10,gte_score_ndcg@10,reasonir_score_ndcg@10,diver_score_ndcg@10,bge_reasoner_score_ndcg@10,task_type,corpus_type
0,trec-covid__test__1,trec-covid,1,EVIDENCE-BASED,what is the origin of COVID-19,test,0.252841,0.039199,0.340113,1.000000,0.716937,0.784617,0.653408,0.501819,0.778429,Bio-Medical Retrieval,Scientific Paper
1,trec-covid__test__2,trec-covid,2,EVIDENCE-BASED,how does the coronavirus respond to changes in...,test,0.613283,0.252841,0.864315,1.000000,1.000000,0.861138,0.926636,1.000000,0.921602,Bio-Medical Retrieval,Scientific Paper
2,trec-covid__test__3,trec-covid,3,DEBATE,will SARS-CoV2 infected people develop immunit...,test,0.195189,0.894275,0.000000,1.000000,0.930569,0.899030,0.827749,0.826422,0.650414,Bio-Medical Retrieval,Scientific Paper
3,trec-covid__test__4,trec-covid,4,EVIDENCE-BASED,what causes death from Covid-19?,test,0.135685,0.110046,0.314880,1.000000,0.966873,0.965284,0.591945,0.957428,0.831848,Bio-Medical Retrieval,Scientific Paper
4,trec-covid__test__5,trec-covid,5,EVIDENCE-BASED,what drugs have been active against SARS-CoV o...,test,0.519520,0.508287,0.283713,1.000000,0.743345,0.546287,0.706663,0.671759,0.571936,Bio-Medical Retrieval,Scientific Paper
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42519,msmarco__test__1132532,msmarco,1132532,FACTOID,average annual income data analyst,test,0.428797,0.835746,0.889954,1.000000,0.978793,0.976856,0.776182,0.770499,0.898255,Passage Retrieval,General Web
42520,msmarco__test__1133579,msmarco,1133579,EVIDENCE-BASED,how does granulation tissue start,test,0.554417,0.629336,0.812214,0.818852,0.817511,0.627877,0.652478,0.676379,0.741429,Passage Retrieval,General Web
42521,msmarco__test__1136043,msmarco,1136043,FACTOID,difference between a hotel and motel,test,0.346317,0.805447,0.724774,0.725397,0.724774,0.723278,0.618023,0.683002,0.593403,Passage Retrieval,General Web
42522,msmarco__test__1136047,msmarco,1136047,FACTOID,difference between a company's strategy and bu...,test,0.459095,0.327582,0.475790,0.557774,0.613942,0.371733,0.433620,0.461970,0.305609,Passage Retrieval,General Web
42523,msmarco__test__1136962,msmarco,1136962,REASON,why did the ancient egyptians call their land ...,test,0.736643,0.693325,0.926636,0.814791,0.848238,0.865011,0.881292,0.880349,0.863444,Passage Retrieval,General Web

In [ ]:
 

data.columns

Index(['query_id', 'dataset_name', 'raw_query_id', 'query_type', 'query_text',
       'split', 'bm25_score_ndcg@10', 'contriever_score_ndcg@10',
       'bge_m3_score_ndcg@10', 'qwen3_score_ndcg@10', 'linq_score_ndcg@10',
       'gte_score_ndcg@10', 'reasonir_score_ndcg@10', 'diver_score_ndcg@10',
       'bge_reasoner_score_ndcg@10', 'task_type', 'corpus_type'],
      dtype='object')

In [ ]:
import pandas as pd
import pingouin as pg
import statsmodels.formula.api as smf

 

# 1. Define your 8 model columns
model_columns = ['bm25_score_ndcg@10',
    'contriever_score_ndcg@10', 'bge_m3_score_ndcg@10', 
    'qwen3_score_ndcg@10', 'linq_score_ndcg@10', 
    'gte_score_ndcg@10', 'reasonir_score_ndcg@10', 
    'diver_score_ndcg@10', 'bge_reasoner_score_ndcg@10'
]

# 2. Define the ID and factor columns required for the analysis.
id_vars = [
    'query_id', 'dataset_name', 'query_type', 
    'task_type', 'corpus_type'
]

# 3. Use pd.melt() to convert wide data to long data.
df_long = pd.melt(
    data,
    id_vars=id_vars,
    value_vars=model_columns,
    var_name='Model_Raw',  # Temporary column name containing '..._score_ndcg@10'
    value_name='ndcg@10'     # Your dependent variable (Y)
)

# 4.Clean up model name
# (For example, 'contriever_score_ndcg@10' -> 'contriever')
df_long['Model'] = df_long['Model_Raw'].str.replace('_score_ndcg@10', '')

# 5. Discard temporary original model columns
df_long = df_long.drop(columns=['Model_Raw'])

# 6. Handle missing values ​​(if any).
df_long = df_long.dropna(subset=['ndcg@10'])

print("Long format data is ready (df_long):")
print(df_long.head())

# Saving Data

# 3. Saving the DataFrame as a CSV File

# Setting index=False is a good practice to prevent pandas from saving the DataFrame's indices (0, 1, 2...) as an extra column in the CSV file.

df_long.to_csv("data/df_long_all_model_scores.csv", index=False)
print(f"\n✅ data saved: data/df_long_all_model_scores.csv")

长格式数据准备完毕 (df_long):
              query_id dataset_name      query_type              task_type  \
0  trec-covid__test__1   trec-covid  EVIDENCE-BASED  Bio-Medical Retrieval
1  trec-covid__test__2   trec-covid  EVIDENCE-BASED  Bio-Medical Retrieval
2  trec-covid__test__3   trec-covid          DEBATE  Bio-Medical Retrieval
3  trec-covid__test__4   trec-covid  EVIDENCE-BASED  Bio-Medical Retrieval
4  trec-covid__test__5   trec-covid  EVIDENCE-BASED  Bio-Medical Retrieval

        corpus_type   ndcg@10 Model
0  Scientific Paper  0.252841  bm25
1  Scientific Paper  0.613283  bm25
2  Scientific Paper  0.195189  bm25
3  Scientific Paper  0.135685  bm25
4  Scientific Paper  0.519520  bm25

✅ 数据已成功保存到: data/df_long_all_model_scores.csv

In [12]:
df_long.shape

(382716, 7)